services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EzPlatform\Menu\MenuItemFactory: ~

    EzPlatform\Menu\MenuItems:
        arguments:
            $translationHelper: '@ezpublish.translation_helper'

    # Main navigation
    EzPlatform\Menu\MainMenuBuilder:
        tags:
            - { name: 'knp_menu.menu_builder', method: 'build', alias: 'site.main_menu' }
